on:
  rss:
    url: ${{ secrets.FEED_URL }}
jobs:
  twitter_1:
    name: Post a tweet 1
    runs-on: ubuntu-latest
    steps:
      - name: Post a tweet 1
        uses: ethomson/send-tweet-action@v1.0.0
        with:
          status: |
              ${{ on.rss.outputs.title }}
              ${{ on.rss.outputs.link }}
          consumer-key: ${{ secrets.TWITTER_CONSUMER_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}
